services:
  my-voting-web:
    build:
      context: .
      dockerfile: apps/my-voting-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - voting-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  my-voting-app:
    build:
      context: .
      dockerfile: apps/my-voting-web/Dockerfile
    ports:
      - "4200:4200"  # Default NX serve port
    volumes:
      - .:/app
      # Named volume for node_modules to prevent overwriting by bind mount
      - my_voting_web_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true  # Enable polling for Windows compatibility
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file watching
    # Keep the container running
    stdin_open: true
    tty: true

volumes:
  my_voting_web_node_modules:

networks:
  voting-network:
    driver: bridge 